CREATE TABLE IF NOT EXISTS `primeirainstancia` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `controleinterno` int(11) NOT NULL,
  `datainicio` date DEFAULT NULL,
  `datalimite` date DEFAULT NULL,
  `dataagendada` date DEFAULT NULL,
  `datareal` date DEFAULT NULL,
  `motivo` int(1) NOT NULL,
  `parecer` int(1) NOT NULL,
  `datapubli` date DEFAULT NULL,
  `datasmul` date DEFAULT NULL,
  `datasmc` date DEFAULT NULL,
  `datasmt` date DEFAULT NULL,
  `datasehab` date DEFAULT NULL,
  `datasiurb` date DEFAULT NULL,
  `datasvma` date DEFAULT NULL,
  `obs` text DEFAULT NULL,
  `datainicio_r` date DEFAULT NULL,
  `datalimite_r` date DEFAULT NULL,
  `dataagendada_r` date DEFAULT NULL,
  `datareal_r` date DEFAULT NULL,
  `motivo_r` int(1) NOT NULL,
  `parecer_r` int(1) NOT NULL,
  `datapubli_r` date DEFAULT NULL,
  `datasmul_r` date DEFAULT NULL,
  `datasmc_r` date DEFAULT NULL,
  `datasmt_r` date DEFAULT NULL,
  `datasehab_r` date DEFAULT NULL,
  `datasiurb_r` date DEFAULT NULL,
  `datasvma_r` date DEFAULT NULL,
  `obs_r` text DEFAULT NULL,
  `complementar` tinyint(1) NOT NULL, 
  `datapublicomplementar` date DEFAULT NULL,  
  `datacumprimento` date DEFAULT NULL,   
  `dataresposta` date DEFAULT NULL,
  `datalimite_c` date DEFAULT NULL,
  `dataagendada_c` date DEFAULT NULL,
  `datareal_c` date DEFAULT NULL,
  `motivo_c` int(1) NOT NULL,
  `parecer_c` int(1) NOT NULL,
  `datapubli_c` date DEFAULT NULL,
  `datasmul_c` date DEFAULT NULL,
  `datasmc_c` date DEFAULT NULL,
  `datasmt_c` date DEFAULT NULL,
  `datasehab_c` date DEFAULT NULL,
  `datasiurb_c` date DEFAULT NULL,
  `datasvma_c` date DEFAULT NULL,
  `obs_c` text DEFAULT NULL, 
  PRIMARY KEY (`id`),
  KEY `fk_graproem_inicial` (`controleinterno`),
  CONSTRAINT `fk_graproem_inicial` FOREIGN KEY (`controleinterno`) REFERENCES `inicial` (`id`) ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

